services:
  bank-postgres:
    image: postgres:16
    container_name: bank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"
    volumes:
      - bank_postgres_data:/var/lib/postgresql/data
    networks:
      - bank-network

volumes:
  bank_postgres_data:

networks:
  bank-network:
